<form action="?" id="login" method="POST">
<table border="0" align="center">
<tbody>
	<tr>
		<td><label for="user_name">Username:</label></td>
		<td><input type="text" name="user_name" id="user_name" maxlength="20" size="20" /></td>
	</tr>
	<tr>
		<td><label for="user_password">Password:</label></td>
		<td><input type="password" name="user_password" id="user_password" maxlength="10" size="10" /></td>
	</tr>
	<tr>
		<td>
			&nbsp;
		</td>

		<td align="right">	
			<input type="submit" name="submit" id="submit" value="Login">
		</td>
	</tr>

	
</tbody>
</table>
</form>