<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Welcome to Full MPG</title>
    <script src="js/libs/modernizr-2.6.2.min.js"></script>
    <script src="js/libs/jquery-1.9.1.min.js"></script>
    <script src="js/libs/jquery-ui-1.10.3.custom.min.js"></script>
    <link type="text/css" rel="stylesheet" href="css/redmond/jquery-ui-1.10.3.custom.css">
    <link type="text/css" rel="stylesheet" href="css/groundwork.css">
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <meta name="viewport">
</head>
<body>
	<div id="header">
		<div class="logo">
		</br>	
			<img src="images/FullMPG.png" alt="Full MPG" Width=350px Height=110px class="center">
		</br>
		</div>
		<nav class="navbar">
            <ul class="row">
              <li class="one small-tablet third"><a href="index.php" title="Return to the homepage">Home</a></li>
              <li class="one small-tablet third"><a href="auth.php" title="Members Only">Members Only</a></li>
              <li class="one small-tablet third"><a href="register.php" title="Register for a new account">Register</a></li>
            </ul>
          </nav>
    </div>
<center>
	<body>